# site settings
title: Refreshcast
subtitle: 
email: youremailaddress@gmail.com
description: Use every episode of your podcast to grow your audience, increase your revenue, and deliver your message. With Refreshcast, dynamically inserted advertisements are just the beginning.
baseurl: "" # the subpath of your site, e.g. /blog
url: # the base hostname & protocol for your site
author:
street_address: 216 N. Mosley 140
city: Wichita
state: KS
zip_code: 67202
country: United States of America
phone: (316) 712-4623

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# social settings
500px_url:
facebook_url:
github_url:
gitlab_url: 
googleplus_url: 
instagram_url: 
linkedin_url: 
pinterest_url:
slack_url:
twitter_url: 

# build settings
markdown: kramdown

sass:
  style: compressed
